export const PRODUCTS = [
  {
    codigo: "P001",
    nombre: "Lámpara LED",
    costo: "5.00",
    precio: "10.00",
    mayoreo: "8.00",
    existencia: "100",
    departamento: "Iluminación",
  },
  {
    codigo: "P002",
    nombre: "Mouse Inalámbrico",
    costo: "7.00",
    precio: "15.00",
    mayoreo: "12.00",
    existencia: "200",
    departamento: "Electrónica",
  },
  {
    codigo: "P003",
    nombre: "Teclado Mecánico",
    costo: "15.00",
    precio: "30.00",
    mayoreo: "25.00",
    existencia: "150",
    departamento: "Electrónica",
  },
  {
    codigo: "P004",
    nombre: "Auriculares Bluetooth",
    costo: "10.00",
    precio: "20.00",
    mayoreo: "16.00",
    existencia: "180",
    departamento: "Electrónica",
  },
  {
    codigo: "P005",
    nombre: "Cafetera",
    costo: "20.00",
    precio: "40.00",
    mayoreo: "35.00",
    existencia: "120",
    departamento: "Electrodomésticos",
  },
  {
    codigo: "P006",
    nombre: "Plancha de Vapor",
    costo: "18.00",
    precio: "36.00",
    mayoreo: "30.00",
    existencia: "130",
    departamento: "Electrodomésticos",
  },
  {
    codigo: "P007",
    nombre: "Reloj Inteligente",
    costo: "25.00",
    precio: "50.00",
    mayoreo: "40.00",
    existencia: "90",
    departamento: "Accesorios",
  },
  {
    codigo: "P008",
    nombre: "Cargador Rápido",
    costo: "8.00",
    precio: "16.00",
    mayoreo: "14.00",
    existencia: "300",
    departamento: "Accesorios",
  },
  {
    codigo: "P009",
    nombre: "Parrilla Eléctrica",
    costo: "22.00",
    precio: "44.00",
    mayoreo: "38.00",
    existencia: "80",
    departamento: "Electrodomésticos",
  },
  {
    codigo: "P010",
    nombre: "Tablet",
    costo: "50.00",
    precio: "100.00",
    mayoreo: "90.00",
    existencia: "70",
    departamento: "Electrónica",
  },
  {
    codigo: "P011",
    nombre: "Cámara de Seguridad",
    costo: "30.00",
    precio: "60.00",
    mayoreo: "50.00",
    existencia: "110",
    departamento: "Seguridad",
  },
  {
    codigo: "P012",
    nombre: "Control Remoto Universal",
    costo: "5.00",
    precio: "10.00",
    mayoreo: "8.00",
    existencia: "250",
    departamento: "Electrónica",
  },
  {
    codigo: "P013",
    nombre: "Microondas",
    costo: "40.00",
    precio: "80.00",
    mayoreo: "70.00",
    existencia: "60",
    departamento: "Electrodomésticos",
  },
  {
    codigo: "P014",
    nombre: "Purificador de Aire",
    costo: "35.00",
    precio: "70.00",
    mayoreo: "60.00",
    existencia: "90",
    departamento: "Hogar",
  },
  {
    codigo: "P015",
    nombre: "Ventilador de Piso",
    costo: "25.00",
    precio: "50.00",
    mayoreo: "45.00",
    existencia: "100",
    departamento: "Hogar",
  },
  {
    codigo: "P016",
    nombre: "Termo",
    costo: "10.00",
    precio: "20.00",
    mayoreo: "15.00",
    existencia: "160",
    departamento: "Cocina",
  },
  {
    codigo: "P017",
    nombre: "Bocina Portátil",
    costo: "12.00",
    precio: "24.00",
    mayoreo: "20.00",
    existencia: "140",
    departamento: "Electrónica",
  },
  {
    codigo: "P018",
    nombre: "Licuadora",
    costo: "18.00",
    precio: "36.00",
    mayoreo: "30.00",
    existencia: "110",
    departamento: "Cocina",
  },
  {
    codigo: "P019",
    nombre: "Aspiradora",
    costo: "28.00",
    precio: "56.00",
    mayoreo: "48.00",
    existencia: "90",
    departamento: "Electrodomésticos",
  },
  {
    codigo: "P020",
    nombre: "Cámara Fotográfica",
    costo: "45.00",
    precio: "90.00",
    mayoreo: "75.00",
    existencia: "70",
    departamento: "Fotografía",
  },
];
